# Generated by Django 3.1.1 on 2021-04-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycledItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reducerName', models.CharField(blank=True, max_length=100, null=True)),
                ('arrayName', models.CharField(blank=True, max_length=100, null=True)),
                ('dateDeleted', models.DateField(blank=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=250, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
