//DEMO
export const RESET_APP = "RESET_APP"

//SETTINGS
export const GET_SETTINGS = "GET_SETTINGS"
export const UPDATE_SETTING = "UPDATE_SETTING"
export const SAVE_SETTING = "SAVE_SETTING"

//CAPITAL
export const ADD_CAPITAL_MOVEMENT = "ADD_CAPITAL_MOVEMENT"
export const GET_CAPITAL = "GET_CAPITAL"
export const UPDATE_CAPITAL = "UPDATE_CAPITAL"
export const SAVE_CAPITAL = "SAVE_CAPITAL"
export const DELETE_CAPITAL = "DELETE_CAPITAL"

//CARRY CALCULATION
export const GET_CARRY = "GET_CARRY"
export const UPDATE_CARRY_SECTION = "UPDATE_CARRY_SECTION"

export const UPDATE_CARRY_CALC = "UPDATE_CARRY_CALC"
export const SAVE_CARRY_CALC = "SAVE_CARRY_CALC"
export const EXPORT_CARRY_CALC = "EXPORT_CARRY_CALC"
export const UPDATE_CARRY_DETAIL = "UPDATE_CARRY_DETAIL"
export const UPDATE_CARRY_COMPARE = "UPDATE_CARRY_COMPARE"
export const SAVE_CLIENT_VALUE = "SAVE_CLIENT_VALUE"
export const SAVE_CLIENT_DETAIL = "SAVE_CLIENT_DETAIL"
export const SAVE_PARAMETER = "SAVE_PARAMETER"
export const SET_CARRY_LOADING = "SET_CARRY_LOADING"

//ALERTS
export const CREATE_SUCCESS = "CREATE_SUCCESS"
export const CREATE_ERROR = "CREATE_ERROR"

// USER ACTION TYPES
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

//EXPORT
export const EXPORT_FILE = "EXPORT_FILE"



//MATERIALITY
export const GET_MATERIALITY = "GET_MATERIALITY"
export const UPDATE_MATERIALITY = "UPDATE_MATERIALITY"

//UPLOADS
export const UPDATE_UPLOADS = "UPDATE_UPLOADS"
export const UPDATE_FILE_OBJECT = "UPDATE_FILE_OBJECT"
export const UPLOAD_IN_PROCESS = "UPLOAD_IN_PROCESS"
export const UPLOAD_FILE = "UPLOAD_FILE"
export const UPLOAD_FILES = "UPLOAD_FILES"
export const ADD_FILE = "ADD_FILE"
export const ADD_FILES = "ADD_FILES"
export const UPDATE_FILE = "UPDATE_FILE"
export const UPDATE_FILE_BY_ID = "UPDATE_FILE_BY_ID"
export const REMOVE_FILE = "REMOVE_FILE"
export const SELECT_FILE = "SELECT_FILE"
export const DELETE_FILE = "DELETE_FILE"
export const UPDATE_FILE_STATUS = "UPDATE_FILE_STATUS"
export const DELETE_ALL_FILES = "DELETE_ALL_FILES"
export const ACCEPT_DUPLICATE_FILE = "ACCEPT_DUPLICATE_FILE"

export const SAVE_FILE = "SAVE_FILE"
export const ACCEPT_FILE = "ACCEPT_FILE"


//SETUP
export const SAVE_FUND_CRITERIA = "SAVE_FUND_CRITERIA"
export const SAVE_INVESTMENT_CRITERIA = "SAVE_INVESTMENT_CRITERIA"
export const SAVE_INVESTOR_CRITERIA = "SAVE_INVESTOR_CRITERIA"



//LAYOUT
export const UPDATE_APP_VIEW = "UPDATE_APP_VIEW"
export const UPDATE_REDIRECT_APP = "UPDATE_REDIRECT_APP"
export const TOGGLE_DATE_VISIBLE = "TOGGLE_DATE_VISIBLE"
export const WINOW_RESIZED = "WINOW_RESIZED"
export const TOGGLE_SIDE_NAV = "TOGGLE_SIDE_NAV"
export const LOCK_LEFT_NAV = "LOCK_LEFT_NAV"
export const TOGGLE_IS_DARK = "TOGGLE_IS_DARK"

export const UPDATE_LAYOUT = 'UPDATE_LAYOUT'

//DATABASE
export const GET_DATABASE = "GET_DATABASE"
export const UPDATE_DATABASE = "UPDATE_DATABASE"


export const UPDATE_DB_OBJECT = "UPDATE_DB_OBJECT"
export const GET_DB_OBJECT = "GET_DB_OBJECT"
export const SAVE_DB_OBJECT = "SAVE_DB_OBJECT"

export const UPDATE_FUND_CLIENT_REPORT_OBJECT = "UPDATE_FUND_CLIENT_REPORT_OBJECT"
export const GET_CLIENT_REPORTS = "GET_CLIENT_REPORTS"
export const SAVE_FUND_CLIENT_REPORT = "SAVE_FUND_CLIENT_REPORT"

//FUNDS
export const GET_FUNDS = "GET_FUNDS"
export const ADD_FUND = "ADD_FUND"
export const UPDATE_FUND = "UPDATE_FUND"
export const DELETE_FUND = "DELETE_FUND"
export const CHANGE_SELECTED_FUND = "CHANGE_SELECTED_FUND"
export const CHANGE_OWNERSHIP_INFO = "CHANGE_OWNERSHIP_INFO"
export const ADD_NEW_OWNERSHIP = "ADD_NEW_OWNERSHIP"
export const GET_ENTITY_OWNERSHIPS = "GET_ENTITY_OWNERSHIPS"
export const DELETE_OWNERSHIP = "DELETE_OWNERSHIP"
export const SAVE_OWNERSHIP = "SAVE_OWNERSHIP"
export const SELECT_OWNERSHIP = "SELECT_OWNERSHIP"
export const GET_FUND_DETAILS = "GET_FUND_DETAILS"

export const GET_ALT_NAMES = "GET_ALT_NAMES"
export const ADD_ALT_FUND_NAME = "ADD_ALT_FUND_NAME"
export const DELETE_ALT_FUND_NAME = "DELETE_ALT_FUND_NAME"
export const SAVE_ALT_FUND_NAME = "SAVE_ALT_FUND_NAME"
export const UPDATE_ALT_FUND_NAME = "UPDATE_ALT_FUND_NAME"


export const TOGGLE_FUND_LOADING = "TOGGLE_FUND_LOADING"
export const ADD_NEW_FUND = "ADD_NEW_FUND"
export const GET_SUPPORT_DATA = "GET_SUPPORT_DATA"

//INVESTMENTS
export const GET_INVESTMENTS = "GET_INVESTMENTS"
export const ADD_INVESTMENT = "ADD_INVESTMENT"
export const DELETE_INVESTMENT = "DELETE_INVESTMENT"
export const UPDATE_INVESTMENT = "UPDATE_INVESTMENT"

export const SET_SEL_INVESTMENT = "SET_SEL_INVESTMENT"
export const TOGGLE_INV_LOADING = "TOGGLE_INV_LOADING"

export const GET_INVESTMENT_DETAILS = "GET_INVESTMENT_DETAILS"


export const GET_INVESTORS = "GET_INVESTORS"
export const UPDATE_INVESTORS = "UPDATE_INVESTORS"
export const SAVE_INVESTOR = "SAVE_INVESTOR"
export const DELETE_INVESTOR = "DELETE_INVESTOR"

//DATES
export const GET_DATES = "GET_DATES"
export const ADD_DATE = "ADD_DATE"
export const DELETE_DATE = "DELETE_DATE"
export const UPDATE_DATE = "UPDATE_DATE"

export const INITIALIZE_MONTHS = "INITIALIZE_MONTHS"


//REPORTS
export const INIT_REPORT = "INIT_REPORT"
export const ADD_REPORT = "ADD_REPORT"
export const UPDATE_REPORTS = "UPDATE_REPORTS"
export const GENERATE_REPORT = "GENERATE_REPORT"
export const DELETE_REPORT = "DELETE_REPORT"


export const GET_REPORT_OPTIONS = "GET_REPORT_OPTIONS"
export const COPY_TO_CLIPBOARD = "COPY_TO_CLIPBOARD"
export const SET_REPORT_FUND_OPTIONS = "SET_REPORT_FUND_OPTIONS"

//PERIODS
export const GET_PERIODS = "GET_PERIODS"
export const SET_SELECTED_PERIOD = "SET_SELECTED_PERIOD"

//TBS
export const GET_TBS = "GET_TBS"
export const GET_TB = "GET_TB"
export const UPDATE_TB = "UPDATE_TB"
export const ADD_TB_MAPPING = "ADD_TB_MAPPING"
export const UPDATE_TB_MAPPING = "UPDATE_TB_MAPPING"
export const DELETE_TB_MAPPING = "DELETE_TB_MAPPING"

//FS
export const GET_FSLIS = "GET_FSLIS"
export const ADD_NEW_FSLI = "ADD_NEW_FSLI"
export const FSLI_TOGGLE_EDIT = "FSLI_TOGGLE_EDIT"


export const ADD_FSLI = "ADD_FSLI"
export const GET_FSLI = "GET_FSLI"
export const SAVE_FSLI = "SAVE_FSLI"
export const SELECT_FSLI = "SELECT_FSLI"

export const UPDATE_FSLI = "UPDATE_FSLI"
export const UPDATE_FSLI_IN_STORE = "UPDATE_FSLI_IN_STORE"
export const DELETE_FSLI = "DELETE_FSLI"
export const UPDATE_FSLI_FILTER = "UPDATE_FSLI_FILTER"
export const UPDATE_SELECTED_FSLI = "UPDATE_SELECTED_FSLI"
export const UPDATE_SELECTED_UNMAPPED = "UPDATE_SELECTED_UNMAPPED"
export const REMOVE_SELECTED_UNMAPPED = "REMOVE_SELECTED_UNMAPPED"
export const GET_UNMAPPED_ACCOUNTS = "GET_UNMAPPED_ACCOUNTS"
export const GET_GENERIC_MAPPINGS = "GET_GENERIC_MAPPINGS"
export const GET_CUSTOM_MAPPINGS = "GET_CUSTOM_MAPPINGS"
export const ADD_GENERIC_MAPPING = "ADD_GENERIC_MAPPING"
export const GET_FS = "GET_FS"

//ADMIN
export const RUN_DB_CHECK = "RUN_DB_CHECK"
export const UPDATE_SETUP_TITLE = "UPDATE_SETUP_TITLE"
export const GET_FUND_OVERVIEW = "GET_FUND_OVERVIEW"
export const TOGGLE_SETUP_MODAL = "TOGGLE_SETUP_MODAL"
export const GET_CLIENT_MAPPINGS = "GET_CLIENT_MAPPINGS"



export const GET_FUNDS_SETUP = "GET_FUNDS_SETUP"
export const UPDATE_FUNDS_SETUP_INPUT = "UPDATE_FUNDS_SETUP_INPUT"
export const SAVE_FUND = "SAVE_FUND"



export const SET_CARRY_REPORT = "SET_CARRY_REPORT"
export const GET_CARRY_SETTINGS = "GET_CARRY_SETTINGS"
export const SET_ENTITY_OPTIONS = "SET_ENTITY_OPTIONS"
export const TOGGLE_OWNERSHIPS_LOADING = "TOGGLE_OWNERSHIPS_LOADING"
export const ADD_CHILD_OWNERSHIP = "ADD_CHILD_OWNERSHIP"




//MAIN
export const GET_CURRENCIES = "GET_CURRENCIES"
export const ADD_CURRENCY = "ADD_CURRENCY"
export const UPDATE_CURRENCY = "UPDATE_CURRENCY"
export const DELETE_CURRENCY = "DELETE_CURRENCY"

export const UPDATE_AUDIT_SETTINGS = "UPDATE_AUDIT_SETTINGS"
export const GET_AUDIT_SETTINGS = "GET_AUDIT_SETTINGS"
export const SAVE_ADUIT_SETTINGS = "SAVE_ADUIT_SETTINGS"
export const ADD_AUDIT_SETTING = "ADD_AUDIT_SETTING"
export const DELETE_AUDIT_SETTING = "DELETE_AUDIT_SETTING"

export const GET_COUNTRIES = "GET_COUNTRIES"
export const GET_COUNTRY = "GET_COUNTRY"
export const ADD_COUNTRY = "ADD_COUNTRY"
export const UPDATE_COUNTRY = "UPDATE_COUNTRY"
export const DELETE_COUNTRY = "DELETE_COUNTRY"

export const GET_GAAPS = "GET_GAAPS"
export const GET_GAAP = "GET_GAAP"
export const ADD_GAAP = "ADD_GAAP"
export const UPDATE_GAAP = "UPDATE_GAAP"
export const DELETE_GAAP = "DELETE_GAAP"

export const GET_AUDITORS = "GET_AUDITORS"
export const GET_AUDITOR = "GET_AUDITOR"
export const ADD_AUDITOR = "ADD_AUDITOR"
export const UPDATE_AUDITOR = "UPDATE_AUDITOR"
export const DELETE_AUDITOR = "DELETE_AUDITOR"


//CASH
export const GET_CASH_MOVEMENTS = "GET_CASH_MOVEMENTS"
export const GET_CASH_MOVEMENT = "GET_CASH_MOVEMENT"
export const ADD_CASH_MOVEMENTS = "ADD_CASH_MOVEMENTS"
export const ADD_CASH_MOVEMENT = "ADD_CASH_MOVEMENT"
export const DELETE_CASH_MOVEMENT = "DELETE_CASH_MOVEMENT"




//SUPPORTS
export const ADD_SUPPORT = "ADD_SUPPORT"
export const GET_SUPPORT = "GET_SUPPORT"
export const GET_SUPPORTS = "GET_SUPPORTS"
export const UPDATE_SUPPORTS = "UPDATE_SUPPORTS"
export const DELETE_SUPPORT = "DELETE_SUPPORT"


//HEALTH
export const GET_DATABASE_HEALTH = "GET_DATABASE_HEALTH"


//REPOSITORY
export const GET_REPOSITORY = "GET_REPOSITORY"
export const UPDATE_REPOSITORY = "UPDATE_REPOSITORY"

export const TOGGLE_REPO_LOADING = "TOGGLE_REPO_LOADING"

export const DELETE_SUPPORT_ITEM = "DELETE_SUPPORT_ITEM"

export const ADD_NEW_REPO_HEADER_TO_STORE = "ADD_NEW_REPO_HEADER_TO_STORE"
export const GET_REPO_TYPES = "GET_REPO_TYPES"
export const REPO_ORDER_SAVED_TO_DB = "REPO_ORDER_SAVED_TO_DB"
export const SAVE_REPOSITORY = "SAVE_REPOSITORY"


//TESTING
export const GET_TESTING_SUMMARY = "GET_TESTING_SUMMARY"
export const GET_TESTING_OVERVIEW = "GET_TESTING_OVERVIEW"
export const GET_QUESTIONAIRE = "GET_QUESTIONAIRE"
export const UPDATE_QUESTIONAIRE = "UPDATE_QUESTIONAIRE"
export const TOGGLE_DETAIL_VIEW = "TOGGLE_DETAIL_VIEW"


export const UPDATE_TESTING_AREAS = "UPDATE_TESTING_AREAS"



export const SET_MATERIALITY = "SET_MATERIALITY"
export const SET_TESTING_VIEW = "SET_TESTING_VIEW"





export const DELETE_CARRY_OTHER_ATTACH = "DELETE_CARRY_OTHER_ATTACH"
export const ADD_CARRY_OTHER_ATTACH = 'ADD_CARRY_OTHER_ATTACH'


export const GET_PROFILES = "GET_PROFILES"
export const SET_SELECTED_PROFILE = "SET_SELECTED_PROFILE"

//RECYCLE BIN
export const GET_RECYCLE_BIN_ITEMS = "GET_RECYCLE_BIN_ITEMS"
export const RECYCLE_ITEM = "RECYCLE_ITEM"
export const DELETE_RECYCLE_ITEM = "DELETE_RECYCLE_ITEM"
export const GET_RECYCLED_ITEMS = "GET_RECYCLED_ITEMS"


//CALENDAR
export const SET_TODAY = "SET_TODAY"
export const CHANGE_CALENDAR_MONTH = "CHANGE_CALENDAR_MONTH"


export const SET_ENTITY_POSITION = "SET_ENTITY_POSITION"
export const CALCULATE_NAVIGATOR_LINES = "CALCULATE_NAVIGATOR_LINES"
export const ADJUST_NAVIGATOR_LINES = "ADJUST_NAVIGATOR_LINES"
export const GET_STRUCTURE = "GET_STRUCTURE"



export const UPDATE_INVESTOR_INFO = "UPDATE_INVESTOR_INFO"
export const ADD_BLOCKER_OWNER = "ADD_BLOCKER_OWNER"
export const GET_BLOCKER_OWNERS = "GET_BLOCKER_OWNERS"
export const SAVE_INVESTOR_UPDATES = "SAVE_INVESTOR_UPDATES"
export const UPDATE_BLOCKER_OWNERSHIP_INFO = "UPDATE_BLOCKER_OWNERSHIP_INFO"
export const SET_SELECTED_BLOCKER = "SET_SELECTED_BLOCKER"
export const TOGGLE_BLOCKER_LOADING = "TOGGLE_BLOCKER_LOADING"
export const DELETE_BLOCKER_OWNERSHIP = "DELETE_BLOCKER_OWNERSHIP"
export const SAVE_BLOCKER_OWNERSHIP = "SAVE_BLOCKER_OWNERSHIP"



