# Generated by Django 3.1.1 on 2021-04-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='date_format',
            field=models.CharField(blank=True, choices=[('MM-DD-YYYY', 'MM-DD-YYYY'), ('DD-MM-YYYY', 'DD-MM-YYYY')], default='MM-DD-YYYY', max_length=50, null=True),
        ),
    ]
