# Generated by Django 3.1.1 on 2021-04-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalmovement',
            name='supportID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
